/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as LoginRouteImport } from './routes/login';
import { Route as AuthRouteImport } from './routes/_auth';
import { Route as AuthIndexRouteImport } from './routes/_auth.index';
import { Route as AuthUsuariosRouteImport } from './routes/_auth.usuarios';
import { Route as AuthUsersRouteImport } from './routes/_auth.users';
import { Route as AuthReportsRouteImport } from './routes/_auth.reports';
import { Route as AuthReportesRouteImport } from './routes/_auth.reportes';
import { Route as AuthPapeleraRouteImport } from './routes/_auth.papelera';
import { Route as AuthMyChildrenRouteImport } from './routes/_auth.my-children';
import { Route as AuthMisPupilosRouteImport } from './routes/_auth.mis-pupilos';
import { Route as AuthMailRouteImport } from './routes/_auth.mail';
import { Route as AuthJustificationsRouteImport } from './routes/_auth.justifications';
import { Route as AuthJustificacionesRouteImport } from './routes/_auth.justificaciones';
import { Route as AuthCursosRouteImport } from './routes/_auth.cursos';
import { Route as AuthCoursesRouteImport } from './routes/_auth.courses';
import { Route as AuthCorreosRouteImport } from './routes/_auth.correos';
import { Route as AuthCalendarioRouteImport } from './routes/_auth.calendario';
import { Route as AuthCalendarRouteImport } from './routes/_auth.calendar';
import { Route as AuthAuditoriaRouteImport } from './routes/_auth.auditoria';
import { Route as AuthAuditRouteImport } from './routes/_auth.audit';
import { Route as AuthAlertasRouteImport } from './routes/_auth.alertas';
import { Route as AuthCursosIndexRouteImport } from './routes/_auth.cursos.index';
import { Route as AuthStudentsStudentIdRouteImport } from './routes/_auth.students.$studentId';
import { Route as AuthCursosCourseIdRouteImport } from './routes/_auth.cursos.$courseId';
import { Route as AuthCoursesCourseIdRouteImport } from './routes/_auth.courses.$courseId';
import { Route as AuthAlumnosStudentIdRouteImport } from './routes/_auth.alumnos.$studentId';

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any);
const AuthUsuariosRoute = AuthUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthRoute,
} as any);
const AuthUsersRoute = AuthUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthRoute,
} as any);
const AuthReportsRoute = AuthReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthRoute,
} as any);
const AuthReportesRoute = AuthReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => AuthRoute,
} as any);
const AuthPapeleraRoute = AuthPapeleraRouteImport.update({
  id: '/papelera',
  path: '/papelera',
  getParentRoute: () => AuthRoute,
} as any);
const AuthMyChildrenRoute = AuthMyChildrenRouteImport.update({
  id: '/my-children',
  path: '/my-children',
  getParentRoute: () => AuthRoute,
} as any);
const AuthMisPupilosRoute = AuthMisPupilosRouteImport.update({
  id: '/mis-pupilos',
  path: '/mis-pupilos',
  getParentRoute: () => AuthRoute,
} as any);
const AuthMailRoute = AuthMailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => AuthRoute,
} as any);
const AuthJustificationsRoute = AuthJustificationsRouteImport.update({
  id: '/justifications',
  path: '/justifications',
  getParentRoute: () => AuthRoute,
} as any);
const AuthJustificacionesRoute = AuthJustificacionesRouteImport.update({
  id: '/justificaciones',
  path: '/justificaciones',
  getParentRoute: () => AuthRoute,
} as any);
const AuthCursosRoute = AuthCursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => AuthRoute,
} as any);
const AuthCoursesRoute = AuthCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AuthRoute,
} as any);
const AuthCorreosRoute = AuthCorreosRouteImport.update({
  id: '/correos',
  path: '/correos',
  getParentRoute: () => AuthRoute,
} as any);
const AuthCalendarioRoute = AuthCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthRoute,
} as any);
const AuthCalendarRoute = AuthCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthRoute,
} as any);
const AuthAuditoriaRoute = AuthAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AuthRoute,
} as any);
const AuthAuditRoute = AuthAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthRoute,
} as any);
const AuthAlertasRoute = AuthAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => AuthRoute,
} as any);
const AuthCursosIndexRoute = AuthCursosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthCursosRoute,
} as any);
const AuthStudentsStudentIdRoute = AuthStudentsStudentIdRouteImport.update({
  id: '/students/$studentId',
  path: '/students/$studentId',
  getParentRoute: () => AuthRoute,
} as any);
const AuthCursosCourseIdRoute = AuthCursosCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => AuthCursosRoute,
} as any);
const AuthCoursesCourseIdRoute = AuthCoursesCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => AuthCoursesRoute,
} as any);
const AuthAlumnosStudentIdRoute = AuthAlumnosStudentIdRouteImport.update({
  id: '/alumnos/$studentId',
  path: '/alumnos/$studentId',
  getParentRoute: () => AuthRoute,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute;
  '/login': typeof LoginRoute;
  '/alertas': typeof AuthAlertasRoute;
  '/audit': typeof AuthAuditRoute;
  '/auditoria': typeof AuthAuditoriaRoute;
  '/calendar': typeof AuthCalendarRoute;
  '/calendario': typeof AuthCalendarioRoute;
  '/correos': typeof AuthCorreosRoute;
  '/courses': typeof AuthCoursesRouteWithChildren;
  '/cursos': typeof AuthCursosRouteWithChildren;
  '/justificaciones': typeof AuthJustificacionesRoute;
  '/justifications': typeof AuthJustificationsRoute;
  '/mail': typeof AuthMailRoute;
  '/mis-pupilos': typeof AuthMisPupilosRoute;
  '/my-children': typeof AuthMyChildrenRoute;
  '/papelera': typeof AuthPapeleraRoute;
  '/reportes': typeof AuthReportesRoute;
  '/reports': typeof AuthReportsRoute;
  '/users': typeof AuthUsersRoute;
  '/usuarios': typeof AuthUsuariosRoute;
  '/alumnos/$studentId': typeof AuthAlumnosStudentIdRoute;
  '/courses/$courseId': typeof AuthCoursesCourseIdRoute;
  '/cursos/$courseId': typeof AuthCursosCourseIdRoute;
  '/students/$studentId': typeof AuthStudentsStudentIdRoute;
  '/cursos/': typeof AuthCursosIndexRoute;
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute;
  '/alertas': typeof AuthAlertasRoute;
  '/audit': typeof AuthAuditRoute;
  '/auditoria': typeof AuthAuditoriaRoute;
  '/calendar': typeof AuthCalendarRoute;
  '/calendario': typeof AuthCalendarioRoute;
  '/correos': typeof AuthCorreosRoute;
  '/courses': typeof AuthCoursesRouteWithChildren;
  '/justificaciones': typeof AuthJustificacionesRoute;
  '/justifications': typeof AuthJustificationsRoute;
  '/mail': typeof AuthMailRoute;
  '/mis-pupilos': typeof AuthMisPupilosRoute;
  '/my-children': typeof AuthMyChildrenRoute;
  '/papelera': typeof AuthPapeleraRoute;
  '/reportes': typeof AuthReportesRoute;
  '/reports': typeof AuthReportsRoute;
  '/users': typeof AuthUsersRoute;
  '/usuarios': typeof AuthUsuariosRoute;
  '/': typeof AuthIndexRoute;
  '/alumnos/$studentId': typeof AuthAlumnosStudentIdRoute;
  '/courses/$courseId': typeof AuthCoursesCourseIdRoute;
  '/cursos/$courseId': typeof AuthCursosCourseIdRoute;
  '/students/$studentId': typeof AuthStudentsStudentIdRoute;
  '/cursos': typeof AuthCursosIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/_auth': typeof AuthRouteWithChildren;
  '/login': typeof LoginRoute;
  '/_auth/alertas': typeof AuthAlertasRoute;
  '/_auth/audit': typeof AuthAuditRoute;
  '/_auth/auditoria': typeof AuthAuditoriaRoute;
  '/_auth/calendar': typeof AuthCalendarRoute;
  '/_auth/calendario': typeof AuthCalendarioRoute;
  '/_auth/correos': typeof AuthCorreosRoute;
  '/_auth/courses': typeof AuthCoursesRouteWithChildren;
  '/_auth/cursos': typeof AuthCursosRouteWithChildren;
  '/_auth/justificaciones': typeof AuthJustificacionesRoute;
  '/_auth/justifications': typeof AuthJustificationsRoute;
  '/_auth/mail': typeof AuthMailRoute;
  '/_auth/mis-pupilos': typeof AuthMisPupilosRoute;
  '/_auth/my-children': typeof AuthMyChildrenRoute;
  '/_auth/papelera': typeof AuthPapeleraRoute;
  '/_auth/reportes': typeof AuthReportesRoute;
  '/_auth/reports': typeof AuthReportsRoute;
  '/_auth/users': typeof AuthUsersRoute;
  '/_auth/usuarios': typeof AuthUsuariosRoute;
  '/_auth/': typeof AuthIndexRoute;
  '/_auth/alumnos/$studentId': typeof AuthAlumnosStudentIdRoute;
  '/_auth/courses/$courseId': typeof AuthCoursesCourseIdRoute;
  '/_auth/cursos/$courseId': typeof AuthCursosCourseIdRoute;
  '/_auth/students/$studentId': typeof AuthStudentsStudentIdRoute;
  '/_auth/cursos/': typeof AuthCursosIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/login'
    | '/alertas'
    | '/audit'
    | '/auditoria'
    | '/calendar'
    | '/calendario'
    | '/correos'
    | '/courses'
    | '/cursos'
    | '/justificaciones'
    | '/justifications'
    | '/mail'
    | '/mis-pupilos'
    | '/my-children'
    | '/papelera'
    | '/reportes'
    | '/reports'
    | '/users'
    | '/usuarios'
    | '/alumnos/$studentId'
    | '/courses/$courseId'
    | '/cursos/$courseId'
    | '/students/$studentId'
    | '/cursos/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/login'
    | '/alertas'
    | '/audit'
    | '/auditoria'
    | '/calendar'
    | '/calendario'
    | '/correos'
    | '/courses'
    | '/justificaciones'
    | '/justifications'
    | '/mail'
    | '/mis-pupilos'
    | '/my-children'
    | '/papelera'
    | '/reportes'
    | '/reports'
    | '/users'
    | '/usuarios'
    | '/'
    | '/alumnos/$studentId'
    | '/courses/$courseId'
    | '/cursos/$courseId'
    | '/students/$studentId'
    | '/cursos';
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/alertas'
    | '/_auth/audit'
    | '/_auth/auditoria'
    | '/_auth/calendar'
    | '/_auth/calendario'
    | '/_auth/correos'
    | '/_auth/courses'
    | '/_auth/cursos'
    | '/_auth/justificaciones'
    | '/_auth/justifications'
    | '/_auth/mail'
    | '/_auth/mis-pupilos'
    | '/_auth/my-children'
    | '/_auth/papelera'
    | '/_auth/reportes'
    | '/_auth/reports'
    | '/_auth/users'
    | '/_auth/usuarios'
    | '/_auth/'
    | '/_auth/alumnos/$studentId'
    | '/_auth/courses/$courseId'
    | '/_auth/cursos/$courseId'
    | '/_auth/students/$studentId'
    | '/_auth/cursos/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren;
  LoginRoute: typeof LoginRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_auth': {
      id: '/_auth';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof AuthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_auth/': {
      id: '/_auth/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof AuthIndexRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_auth/usuarios': {
      id: '/_auth/usuarios';
      path: '/usuarios';
      fullPath: '/usuarios';
      preLoaderRoute: typeof AuthUsuariosRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_auth/users': {
      id: '/_auth/users';
      path: '/users';
      fullPath: '/users';
      preLoaderRoute: typeof AuthUsersRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_auth/reports': {
      id: '/_auth/reports';
      path: '/reports';
      fullPath: '/reports';
      preLoaderRoute: typeof AuthReportsRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_auth/reportes': {
      id: '/_auth/reportes';
      path: '/reportes';
      fullPath: '/reportes';
      preLoaderRoute: typeof AuthReportesRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_auth/my-children': {
      id: '/_auth/my-children';
      path: '/my-children';
      fullPath: '/my-children';
      preLoaderRoute: typeof AuthMyChildrenRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_auth/papelera': {
      id: '/_auth/papelera';
      path: '/papelera';
      fullPath: '/papelera';
      preLoaderRoute: typeof AuthPapeleraRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_auth/mis-pupilos': {
      id: '/_auth/mis-pupilos';
      path: '/mis-pupilos';
      fullPath: '/mis-pupilos';
      preLoaderRoute: typeof AuthMisPupilosRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_auth/mail': {
      id: '/_auth/mail';
      path: '/mail';
      fullPath: '/mail';
      preLoaderRoute: typeof AuthMailRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_auth/justifications': {
      id: '/_auth/justifications';
      path: '/justifications';
      fullPath: '/justifications';
      preLoaderRoute: typeof AuthJustificationsRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_auth/justificaciones': {
      id: '/_auth/justificaciones';
      path: '/justificaciones';
      fullPath: '/justificaciones';
      preLoaderRoute: typeof AuthJustificacionesRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_auth/cursos': {
      id: '/_auth/cursos';
      path: '/cursos';
      fullPath: '/cursos';
      preLoaderRoute: typeof AuthCursosRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_auth/courses': {
      id: '/_auth/courses';
      path: '/courses';
      fullPath: '/courses';
      preLoaderRoute: typeof AuthCoursesRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_auth/correos': {
      id: '/_auth/correos';
      path: '/correos';
      fullPath: '/correos';
      preLoaderRoute: typeof AuthCorreosRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_auth/calendario': {
      id: '/_auth/calendario';
      path: '/calendario';
      fullPath: '/calendario';
      preLoaderRoute: typeof AuthCalendarioRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_auth/calendar': {
      id: '/_auth/calendar';
      path: '/calendar';
      fullPath: '/calendar';
      preLoaderRoute: typeof AuthCalendarRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_auth/auditoria': {
      id: '/_auth/auditoria';
      path: '/auditoria';
      fullPath: '/auditoria';
      preLoaderRoute: typeof AuthAuditoriaRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_auth/audit': {
      id: '/_auth/audit';
      path: '/audit';
      fullPath: '/audit';
      preLoaderRoute: typeof AuthAuditRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_auth/alertas': {
      id: '/_auth/alertas';
      path: '/alertas';
      fullPath: '/alertas';
      preLoaderRoute: typeof AuthAlertasRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_auth/cursos/': {
      id: '/_auth/cursos/';
      path: '/';
      fullPath: '/cursos/';
      preLoaderRoute: typeof AuthCursosIndexRouteImport;
      parentRoute: typeof AuthCursosRoute;
    };
    '/_auth/students/$studentId': {
      id: '/_auth/students/$studentId';
      path: '/students/$studentId';
      fullPath: '/students/$studentId';
      preLoaderRoute: typeof AuthStudentsStudentIdRouteImport;
      parentRoute: typeof AuthRoute;
    };
    '/_auth/cursos/$courseId': {
      id: '/_auth/cursos/$courseId';
      path: '/$courseId';
      fullPath: '/cursos/$courseId';
      preLoaderRoute: typeof AuthCursosCourseIdRouteImport;
      parentRoute: typeof AuthCursosRoute;
    };
    '/_auth/courses/$courseId': {
      id: '/_auth/courses/$courseId';
      path: '/$courseId';
      fullPath: '/courses/$courseId';
      preLoaderRoute: typeof AuthCoursesCourseIdRouteImport;
      parentRoute: typeof AuthCoursesRoute;
    };
    '/_auth/alumnos/$studentId': {
      id: '/_auth/alumnos/$studentId';
      path: '/alumnos/$studentId';
      fullPath: '/alumnos/$studentId';
      preLoaderRoute: typeof AuthAlumnosStudentIdRouteImport;
      parentRoute: typeof AuthRoute;
    };
  }
}

interface AuthCoursesRouteChildren {
  AuthCoursesCourseIdRoute: typeof AuthCoursesCourseIdRoute;
}

const AuthCoursesRouteChildren: AuthCoursesRouteChildren = {
  AuthCoursesCourseIdRoute: AuthCoursesCourseIdRoute,
};

const AuthCoursesRouteWithChildren = AuthCoursesRoute._addFileChildren(AuthCoursesRouteChildren);

interface AuthCursosRouteChildren {
  AuthCursosCourseIdRoute: typeof AuthCursosCourseIdRoute;
  AuthCursosIndexRoute: typeof AuthCursosIndexRoute;
}

const AuthCursosRouteChildren: AuthCursosRouteChildren = {
  AuthCursosCourseIdRoute: AuthCursosCourseIdRoute,
  AuthCursosIndexRoute: AuthCursosIndexRoute,
};

const AuthCursosRouteWithChildren = AuthCursosRoute._addFileChildren(AuthCursosRouteChildren);

interface AuthRouteChildren {
  AuthAlertasRoute: typeof AuthAlertasRoute;
  AuthAuditRoute: typeof AuthAuditRoute;
  AuthAuditoriaRoute: typeof AuthAuditoriaRoute;
  AuthCalendarRoute: typeof AuthCalendarRoute;
  AuthCalendarioRoute: typeof AuthCalendarioRoute;
  AuthCorreosRoute: typeof AuthCorreosRoute;
  AuthCoursesRoute: typeof AuthCoursesRouteWithChildren;
  AuthCursosRoute: typeof AuthCursosRouteWithChildren;
  AuthJustificacionesRoute: typeof AuthJustificacionesRoute;
  AuthJustificationsRoute: typeof AuthJustificationsRoute;
  AuthMailRoute: typeof AuthMailRoute;
  AuthMisPupilosRoute: typeof AuthMisPupilosRoute;
  AuthMyChildrenRoute: typeof AuthMyChildrenRoute;
  AuthPapeleraRoute: typeof AuthPapeleraRoute;
  AuthReportesRoute: typeof AuthReportesRoute;
  AuthReportsRoute: typeof AuthReportsRoute;
  AuthUsersRoute: typeof AuthUsersRoute;
  AuthUsuariosRoute: typeof AuthUsuariosRoute;
  AuthIndexRoute: typeof AuthIndexRoute;
  AuthAlumnosStudentIdRoute: typeof AuthAlumnosStudentIdRoute;
  AuthStudentsStudentIdRoute: typeof AuthStudentsStudentIdRoute;
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAlertasRoute: AuthAlertasRoute,
  AuthAuditRoute: AuthAuditRoute,
  AuthAuditoriaRoute: AuthAuditoriaRoute,
  AuthCalendarRoute: AuthCalendarRoute,
  AuthCalendarioRoute: AuthCalendarioRoute,
  AuthCorreosRoute: AuthCorreosRoute,
  AuthCoursesRoute: AuthCoursesRouteWithChildren,
  AuthCursosRoute: AuthCursosRouteWithChildren,
  AuthJustificacionesRoute: AuthJustificacionesRoute,
  AuthJustificationsRoute: AuthJustificationsRoute,
  AuthMailRoute: AuthMailRoute,
  AuthMisPupilosRoute: AuthMisPupilosRoute,
  AuthMyChildrenRoute: AuthMyChildrenRoute,
  AuthPapeleraRoute: AuthPapeleraRoute,
  AuthReportesRoute: AuthReportesRoute,
  AuthReportsRoute: AuthReportsRoute,
  AuthUsersRoute: AuthUsersRoute,
  AuthUsuariosRoute: AuthUsuariosRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthAlumnosStudentIdRoute: AuthAlumnosStudentIdRoute,
  AuthStudentsStudentIdRoute: AuthStudentsStudentIdRoute,
};

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
