ALTER TABLE `user_school_roles`
  MODIFY COLUMN `role` ENUM('SUPER_ADMIN', 'DIRECTOR', 'UTP', 'INSPECTORIA', 'PROFESOR', 'APODERADO') NOT NULL;

ALTER TABLE `school_permissions`
  MODIFY COLUMN `role` ENUM('SUPER_ADMIN', 'DIRECTOR', 'UTP', 'INSPECTORIA', 'PROFESOR', 'APODERADO') NOT NULL;
